name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_check:
    name: Check Terraform Configuration
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.4"

      - name: Terraform Init
        run: terraform -chdir=./terraform/development init 

      - name: Terraform Validate
        run: terraform -chdir=./terraform/development validate -no-color 

  terraform_apply:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init -reconfigure ./terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve ./terraform/${{ env.TF_ENV }}
