name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  terraform_check:
    name: Check Terraform Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Modified Directories
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          
          MODIFIED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^terraform/env/' | awk -F'/' '{print $3}' | sort -u)
          echo "MODIFIED_DIRS=$MODIFIED_DIRS" >> $GITHUB_ENV

      - name: Print Modified Directories
        run: |
          echo "Modified directories: $MODIFIED_DIRS"

  #     - name: Set up Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: "1.7.4"

  #     - name: Terraform Init
  #       run: terraform -chdir=./terraform/development init 

  #     - name: Terraform Validate
  #       run: terraform -chdir=./terraform/development validate -no-color 

  # terraform_apply:
  #   name: Apply Terraform Changes
  #   runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: Set up Terraform
    #     uses: hashicorp/setup-terraform@v1
    #     with:
    #       terraform_version: 1.0.0

    #   - name: Terraform Init
    #     run: terraform init -reconfigure ./terraform/

    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve ./terraform/${{ env.TF_ENV }}
