name: Terraform CI/CD

on:
  workflow_dispatch:
  

jobs:
  terraform_check:
    name: Check Terraform Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.4"

      - name: Terraform Init
        run: terraform init -backend=false ./terraform/${{ github.event_name }}

      - name: Terraform Validate
        run: terraform validate -no-color ./terraform/${{ github.event_name }}

  terraform_apply:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init -reconfigure ./terraform/${{ env.TF_ENV }}

      - name: Terraform Apply
        run: terraform apply -auto-approve ./terraform/${{ env.TF_ENV }}
